### ISSUE TITLE
Unable to delete key

### ISSUE THREAD

**Issue by foobargeez** [hexfusion/perl-net-etcd#24]
Running something like `$etcd->range({key => "$key"})->delete` isn't deleting the key.  Doing a manual `etcdctl --endpoints <etcdhost> del <key>` works just fine.  Note that I am able to set a key using the module just fine.

Running Net::Etcd v0.013 and etcd v3.2.5 ... 

Thanks!

**Comment by hexfusion** [comment]
@foobargeez appreciate the report I will check this out. Can you confirm you have ETCDCTL_API=3 set? Thanks!

**Comment by foobargeez** [comment]
Thanks for looking into it.  Yes, I do have `$ENV{ETCDCTL_API}=3`.

**Comment by hexfusion** [comment]
:+1:

**Comment by foobargeez** [comment]
I dug the issue and am able to put a hack to make it work.  The issue is that $self object being passed to `delete()` is a response from AnyEvent::HTTP.  I deleted the following in $self object so I can call grpc-proxy again:

```
$self->{request}
$self->{headers}
$self->{response}
```

The part that I am not sure about is, `deleterange` is an independent endpoint (ref: https://coreos.com/etcd/docs/latest/dev-guide/apispec/swagger/rpc.swagger.json), so I don't really see why we should hit grpc-proxy twice, once for range({}) and second for delete().  Perhaps, we should move `deleterange` under Net::Etcd::KV and expose it independently!?

I am happy to submit a PR once we agree on the approach.

Thanks!

**Comment by hexfusion** [comment]
@foobargeez yes it is a bug for sure.  The way that range is called is the problem we are returning a response before delete in invoked. If you look at the way User.pm is done that falls inline with what your saying as desired functionality.  So let define deleterange in Etcd.pm making the call directly to Range.pm but this time the request is only against the delete endpoint. If that makes sense a PR would be great. I will try to get more involved in a bit, w$rk.

**Comment by foobargeez** [comment]
> So let define deleterange in Etcd.pm making the call directly to Range.pm but this time the request is only against the delete endpoint.

`/kv/range` is an independent endpoint too (ref: https://coreos.com/etcd/docs/latest/dev-guide/apispec/swagger/rpc.swagger.json), so `$self->range({})` should continue to do what it is doing now.  I was thinking more along the lines of `range` or `put` where we `deleterange` will be called as `Net::Etcd::KV::DeleteRange`.  If my understanding is right, it is an independent endpoint on grpc-proxy, so we should be able to call it independently.

Thoughts?

**Comment by foobargeez** [comment]
I am about to submit a PR but I am getting 403.  Do you have to tweak any settings in the repo for others to be able to submit PR?

**Comment by foobargeez** [comment]
Submitted https://github.com/hexfusion/perl-net-etcd/pull/25.  Please review and let me know what you think.  Thanks!

**Comment by hexfusion** [comment]
Fixed via https://github.com/hexfusion/perl-net-etcd/pull/25 @foobargeez :+1:

**Comment by hexfusion** [comment]
This is now on it's way to CPAN as v0.014
