### ISSUE TITLE
Add endpoints

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/perl-net-etcd#41]
Currently we define a single etcd host/port this is really not great. We need to add an array of endpoints in the same way etcdctl does. Then we can use those endpoints to return health etc for the cluster. When multiple endpoints are defined we randomly use one and fallback to next in case of timeout.

**Comment by hexfusion** [comment]
@foobargeez are you interested in taking a stab at this?

**Comment by foobargeez** [comment]
Sure, will look into it this week.
