### ISSUE TITLE
How to realize "--prefix=true" as in etcdctl?

### ISSUE THREAD

**Issue by michaelfung** [hexfusion/perl-net-etcd#53]
Hello,

I want to grant permission to every node under '/pub/'. What I do now is:
```
$etcd->role_perm({
    name => 'guest',
    key => '/pub/',
    range_end => "\0",
    permType => 'READWRITE'
})->grant;  
```

Is it okay to stay like this , or is it better to do something like "--prefix=true" as in etcdctl?

Thanks,
Michael

**Comment by hexfusion** [comment]
@michaelfung I think this is a useful feature. The usage would be prefix => 1 or any other perly true value.

**Comment by michaelfung** [comment]
Thanks! But it seems etcdctl does not achieve prefix by setting range_end to "\0".

**Comment by hexfusion** [comment]
I am open to a PR if you have different thoughts on a solution.
