### ISSUE TITLE
Undefined value handling in callback from AnyEvent::HTTP::http_request

### ISSUE THREAD

**Issue by jk-mtnv** [hexfusion/perl-net-etcd#69]
Hello,

I have observed that the request method does not handle situations where it receives an undefined value in its callback from the AnyEvent::HTTP::http_request function, particularly in cases of HTTP errors (e.g., non-200 status codes).

Expected Behavior

The request method should handle undefined values gracefully. It should either:
- Terminate with a clear and descriptive error message, or
- Return a response object that indicates the error, thereby allowing the library user to handle the error appropriately.

Actual Behavior

Currently, the request method dies with the following message:
`Can't call method "on_read" on an undefined value at Etcd/Role/Actions.pm line 235.`

**NB!**
I have proposed a PR for the issue. Please feel free to review it, and I would appreciate any feedback.

**Comment by hexfusion** [comment]
Sounds good please raise and I will review
